### PR TITLE
Update 06-topic-models.Rmd

### PR DESCRIPTION
**Pull request by PursuitOfDataScience**
Missed ")".

### CODE REVIEW

**Comment by juliasilge** [comment]
Thank you so much @PursuitOfDataScience! 🙌

**Comment by PursuitOfDataScience** [comment]
You are welcome @juliasilge 
For some reason, the tidytext mining [website](https://www.tidytextmining.com/) doesn't exist anymore. Not sure what happened.

**Comment by juliasilge** [comment]
Hmmm, something has gone wrong. I have rolled back to a previous deploy and I'll work on this soon.

**Comment by juliasilge** [comment]
OK, I believe I got it sorted after updating the GH action! 👍

**Pull request merged**
